export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST';
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS';
export const PRODUCTS_FAILURE = 'PRODUCTS_FAILURE';

export const GET_FILTERDATA_SUCCESS = "GET_FILTERDATA_SUCCESS";

export const LOW_TO_HIGH = "LOW_TO_HIGH";
export const HIGH_TO_LOW = "HIGH_TO_LOW";